// usercenter_rpc.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: usercenter_rpc.proto

package usercenter_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsercenterRpc_GetUserInfo_FullMethodName = "/usercenter_rpc.Usercenter_rpc/GetUserInfo"
)

// UsercenterRpcClient is the client API for UsercenterRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 根据 Usercenter_rpc 直接生成了 usercenterrpc.go
// 就是生成了一个客户端 通过调用方法可以直接和 server 交互
// internal/server/usercenterrpcserver.go
type UsercenterRpcClient interface {
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
}

type usercenterRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewUsercenterRpcClient(cc grpc.ClientConnInterface) UsercenterRpcClient {
	return &usercenterRpcClient{cc}
}

func (c *usercenterRpcClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResp)
	err := c.cc.Invoke(ctx, UsercenterRpc_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsercenterRpcServer is the server API for UsercenterRpc service.
// All implementations must embed UnimplementedUsercenterRpcServer
// for forward compatibility.
//
// 根据 Usercenter_rpc 直接生成了 usercenterrpc.go
// 就是生成了一个客户端 通过调用方法可以直接和 server 交互
// internal/server/usercenterrpcserver.go
type UsercenterRpcServer interface {
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error)
	mustEmbedUnimplementedUsercenterRpcServer()
}

// UnimplementedUsercenterRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsercenterRpcServer struct{}

func (UnimplementedUsercenterRpcServer) GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUsercenterRpcServer) mustEmbedUnimplementedUsercenterRpcServer() {}
func (UnimplementedUsercenterRpcServer) testEmbeddedByValue()                       {}

// UnsafeUsercenterRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsercenterRpcServer will
// result in compilation errors.
type UnsafeUsercenterRpcServer interface {
	mustEmbedUnimplementedUsercenterRpcServer()
}

func RegisterUsercenterRpcServer(s grpc.ServiceRegistrar, srv UsercenterRpcServer) {
	// If the following call pancis, it indicates UnimplementedUsercenterRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsercenterRpc_ServiceDesc, srv)
}

func _UsercenterRpc_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterRpcServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsercenterRpc_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterRpcServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UsercenterRpc_ServiceDesc is the grpc.ServiceDesc for UsercenterRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsercenterRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usercenter_rpc.Usercenter_rpc",
	HandlerType: (*UsercenterRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UsercenterRpc_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usercenter_rpc.proto",
}
