// usercenter_rpc.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: usercenter_rpc.proto

package usercenter_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_usercenter_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_usercenter_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_usercenter_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_usercenter_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_usercenter_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_usercenter_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserInfoResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

var File_usercenter_rpc_proto protoreflect.FileDescriptor

const file_usercenter_rpc_proto_rawDesc = "" +
	"\n" +
	"\x14usercenter_rpc.proto\x12\x0eusercenter_rpc\" \n" +
	"\x0eGetUserInfoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\x0fGetUserInfoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname2`\n" +
	"\x0eUsercenter_rpc\x12N\n" +
	"\vGetUserInfo\x12\x1e.usercenter_rpc.GetUserInfoReq\x1a\x1f.usercenter_rpc.GetUserInfoRespB\x12Z\x10./usercenter_rpcb\x06proto3"

var (
	file_usercenter_rpc_proto_rawDescOnce sync.Once
	file_usercenter_rpc_proto_rawDescData []byte
)

func file_usercenter_rpc_proto_rawDescGZIP() []byte {
	file_usercenter_rpc_proto_rawDescOnce.Do(func() {
		file_usercenter_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usercenter_rpc_proto_rawDesc), len(file_usercenter_rpc_proto_rawDesc)))
	})
	return file_usercenter_rpc_proto_rawDescData
}

var file_usercenter_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_usercenter_rpc_proto_goTypes = []any{
	(*GetUserInfoReq)(nil),  // 0: usercenter_rpc.GetUserInfoReq
	(*GetUserInfoResp)(nil), // 1: usercenter_rpc.GetUserInfoResp
}
var file_usercenter_rpc_proto_depIdxs = []int32{
	0, // 0: usercenter_rpc.Usercenter_rpc.GetUserInfo:input_type -> usercenter_rpc.GetUserInfoReq
	1, // 1: usercenter_rpc.Usercenter_rpc.GetUserInfo:output_type -> usercenter_rpc.GetUserInfoResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_usercenter_rpc_proto_init() }
func file_usercenter_rpc_proto_init() {
	if File_usercenter_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usercenter_rpc_proto_rawDesc), len(file_usercenter_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usercenter_rpc_proto_goTypes,
		DependencyIndexes: file_usercenter_rpc_proto_depIdxs,
		MessageInfos:      file_usercenter_rpc_proto_msgTypes,
	}.Build()
	File_usercenter_rpc_proto = out.File
	file_usercenter_rpc_proto_goTypes = nil
	file_usercenter_rpc_proto_depIdxs = nil
}
